<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="my" nsURI="http://micael.org/my" nsPrefix="micael.org">
  <eClassifiers xsi:type="ecore:EClass" name="Config"/>
  <eClassifiers xsi:type="ecore:EClass" name="IName" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="other" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ID" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        changeable="false"/>
  </eClassifiers>
  <eSubpackages name="domain" nsURI="http://micael.org/my.domain" nsPrefix="micael.org">
    <eClassifiers xsi:type="ecore:EClass" name="User" eSuperTypes="#//ID #//IName">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="birthday" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="organization" eType="#//domain/Organization"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="groups" upperBound="-1"
          eType="#//domain/Group" eOpposite="#//domain/Group/users"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Group" eSuperTypes="#//ID #//IName">
      <eStructuralFeatures xsi:type="ecore:EReference" name="users" upperBound="-1"
          eType="#//domain/User" eOpposite="#//domain/User/groups"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Organization" eSuperTypes="#//ID #//IName"/>
  </eSubpackages>
</ecore:EPackage>
